version: '3'

services:
  libreddit:
    image: libreddit/libreddit:latest
    container_name: libreddit
    restart: unless-stopped
    networks:
      - frontend
    security_opt:
      - no-new-privileges:true
    environment:
      LIBREDDIT_DEFAULT_AUTOPLAY_VIDEOS: 'off'
      LIBREDDIT_DEFAULT_COMMENT_SORT: 'top'
      LIBREDDIT_DEFAULT_HIDE_HLS_NOTIFICATION: 'on'
      LIBREDDIT_DEFAULT_LAYOUT: 'card'
      LIBREDDIT_DEFAULT_POST_SORT: 'confidence'
      LIBREDDIT_DEFAULT_SHOW_NSFW: 'on'
      LIBREDDIT_DEFAULT_THEME: 'dark'
      LIBREDDIT_DEFAULT_USE_HLS: 'on'
      LIBREDDIT_DEFAULT_BLUR_NSFW: 'on'
networks:
  frontend:
    external: true
