version: "3"

services:
  ownfoil:
    container_name: ownfoil
    image: a1ex4/ownfoil
    environment:
      - PUID=1000
      - PGID=1000
      - USERNAME=$USERNAME
      - PASSWORD=$PASSWORD
      - SAVE_ENABLED=true
    volumes:
      - ${DOCKER}/apps/${APP}/games:/games
    ports:
      - "8000:80"
