version: "3.7"
services:
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr
    container_name: prowlarr
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - frontend
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - UMASK=002
      - TZ=$TZ
    volumes:
      - ${DOCKER}/apps/${APP}/config:/config
networks:
  frontend:
    external: true
