default_config:

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/hass-hue-icons/hass-hue-icons.js
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zone: !include zone.yaml
automation: !include automations.yaml
sensor: !include sensor.yaml

homeassistant:
  external_url: https://hassio.example.net
  internal_url: http://192.168.1.57:2083

http:
  ip_ban_enabled: true
  server_port: 2083
  login_attempts_threshold: 5
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - 173.245.48.0/20
    - 103.21.244.0/22
    - 103.22.200.0/22
    - 103.31.4.0/22
    - 141.101.64.0/18
    - 108.162.192.0/18
    - 190.93.240.0/20
    - 188.114.96.0/20
    - 197.234.240.0/22
    - 198.41.128.0/17
    - 162.158.0.0/15
    - 104.16.0.0/13
    - 104.24.0.0/14
    - 172.64.0.0/13
    - 131.0.72.0/22
    - 172.30.33.0/24

influxdb:
  host: 192.168.1.57
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Vizio TV
vizio:
  - host: 192.168.10.100
    access_token: 8899

# Speedtest
speedtestdotnet:
  scan_interval:
    minutes: 30
  monitored_conditions:
    - download
    - upload
    - ping

# iCloud
calendar:
  - platform: caldav
    username: !secret icloud_username
    password: !secret icloud_app_specific_password
    url: !secret icloud_url
    calendars:
      - Personal
      - Work
