version: '3.3'
services:
    fgc-1:
        image: ghcr.io/vogler/free-games-claimer
        container_name: fgc-1
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        command: bash -c " node prime-gaming; node gog; echo sleeping; sleep 1d"
        ports:
            - '6080:6080'
        volumes:
            - '${DOCKER}/apps/${APP}/profiles/1:/fgc/data'
        environment:
            - NOTIFY='ntfy://ntfy.local.example.com/games'

    fgc-2:
        image: ghcr.io/vogler/free-games-claimer
        container_name: fgc-2
        restart: unless-stopped
        security_opt:
            - no-new-privileges:true
        command: bash -c "echo waiting 10 minutes; sleep 10m; node gog; echo sleeping; sleep 1d"
        ports:
            - '6081:6080'
        volumes:
            - '${DOCKER}/apps/${APP}/profiles/2:/fgc/data'
        environment:
            - NOTIFY='ntfy://ntfy.local.example.com/games'
