version: "3"
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - DOZZLE_NO_ANALYTICS=false
networks:
  default:
    name: frontend
    external: true
