version: "2.3"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command:
      - serve
    environment:
      - TZ=$TZ
    user: $UID:$GID
    volumes:
      - ${DOCKER}/apps/${APP}/cache:/var/cache/ntfy
      - ${DOCKER}/apps/${APP}/data:/etc/ntfy
      - ${DOCKER}/apps/${APP}/data:/var/lib/ntfy/
    networks:
      - frontend
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped
networks:
  frontend:
    external: true
