services:

  caddy:
    build: ./dockerfile-caddy
    container_name: caddy
    hostname: caddy
    restart: unless-stopped
    environment:
      - MY_DOMAIN
      - CLOUDFLARE_API_TOKEN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ${DOCKER}/apps/${APP}/Caddyfile:/etc/caddy/Caddyfile
      - ${DOCKER}/apps/${APP}/config:/config
      - ${DOCKER}/apps/${APP}/data:/data
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
networks:
  default:
    name: $DOCKER_MY_NETWORK
    external: true
