version: '2'
services:
  thelounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: thelounge
    ports:
      - "9000:9000"
    restart: always
    volumes:
      - ${DOCKER}/apps/${APP}:/var/opt/thelounge
