version: "3"
services:
  gitea:
    image: gitea/gitea:1.20.5
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=$PASSWORD
    restart: unless-stopped
    network_mode: gitea
    volumes:
      - ${DOCKER}/apps/${APP}/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gitea-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$ROOT_PASSWORD
      - MYSQL_USER=gitea
      - MYSQL_PASSWORD=$PASSWORD
      - MYSQL_DATABASE=gitea
    network_mode: gitea
    volumes:
      - ${DOCKER}/dbs/${APP}/mysql:/var/lib/mysql
